backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

# https://www.netlifycms.org/docs/add-to-your-site/#media-and-public-folders
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "books"
    label: "Book"
    folder: "src/data/books"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: json
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "book"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Quotes", name: "quotes", widget: "list",
         fields: [{label: "Text", widget: "markdown", name: "text"}]}